name: artic-ebov
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.70=np112py36_1
  - bwa=0.7.17=pl5.22.0_2
  - clint=0.5.1=py36_0
  - eigen=3.2=3
  - ete3=3.1.1=py36_0
  - goalign=0.2.8=0
  - gotree=0.2.10=0
  - libdeflate=0.8=0
  - muscle=3.8.1551=2
  - nanopolish=0.9.2=py36_ncurses5.9_4
  - phyml=3.3.20170530=0
  - porechop=0.2.3_seqan2.1.1=py36_2
  - pandas=0.23.0=py36_1
  - samtools=1.8=4
  - muscle=3.8.1551=2
  - phyml=3.3.20170530=0
  - goalign=0.2.8=0
  - gotree=0.2.10=0
  - ete3=3.1.1=py36_0
